# Generated by Django 6.0.2 on 2026-02-07 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movies_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 7, 9, 18, 8, 965734, tzinfo=datetime.timezone.utc)),
        ),
    ]
