# Generated by Django 6.0.2 on 2026-02-07 09:18

import django.utils.timezone  # pyright: ignore[reportMissingModuleSource]
from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movies_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
